require("serii.core.options")
require("serii.core.colorscheme")
require("serii.core.keymaps")
require("serii.plugins-setup")

-- plugins
require("serii.plugins.nvim-tree")
require("serii.plugins.lualine")
require("serii.plugins.telescope")
require("serii.plugins.toggleterm")
require("serii.plugins.bufferline")
require("serii.plugins.lsp.mason")
require("serii.plugins.lsp.mason-lspconfig")
require("serii.plugins.lsp.lspconfig")
require("serii.plugins.nvim-cmp")
require("serii.plugins.flash")
require("serii.plugins.notify")
require("serii.plugins.noice")
require("serii.plugins.emmet")
require("serii.plugins.ultisnipets")
require("serii.plugins.indent-guides")
require("serii.plugins.rainbow")
require("serii.plugins.treesitter")
